swagger: "2.0"
info:
  description: "admin api"
  version: "1.0.0"
  title: "admin api"
host: "39.98.58.238:8082"
basePath: "/api"
tags:
- name: "account"
  description: "account"
- name: "jadepool"
  description: "jadepool"
- name: "blockchain"
  description: "blockchain"
schemes:
- "https"
- "http"
paths:
  /account/new:
    post:
      tags:
      - "account"
      summary: "create a account"
      description: ""
      operationId: "newAccount"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "account object"
        required: true
        schema:
          $ref: "#/definitions/Account"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
  /account/login:
    post:
      tags:
      - "account"
      summary: "login"
      description: ""
      operationId: "login"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "account object"
        required: true
        schema:
          type: "object"
          required:
          - "name"
          - "password"
          properties:
            name:
              type: "string"
            password:
              type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              status:
                type: "boolean"
              message:
                type: "string"
              data:
                type: "object"
                properties:
                  token: 
                    type: "string"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
  /jadepool:
    get:
      tags:
      - "jadepool"
      summary: "get jadepool list"
      description: ""
      operationId: "getJadepoolList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              status:
                type: "boolean"
              message:
                type: "string"
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Jadepool"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
      security:
      - bearerAuth: []
  /jadepool/new:
    post:
      tags:
      - "jadepool"
      summary: "create a jadepool"
      description: ""
      operationId: "newJadepool"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "jadepool object"
        required: true
        schema:
          $ref: "#/definitions/Jadepool"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
      security:
      - bearerAuth: []
  /jadepool/{id}:
    put:
      tags:
      - "jadepool"
      summary: "update a jadepool"
      description: ""
      operationId: "updateJadepool"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "jadepool id"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "jadepool object"
        required: true
        schema:
          $ref: "#/definitions/Jadepool"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
      security:
      - bearerAuth: []
    get:
      tags:
      - "jadepool"
      summary: "get a jadepool"
      description: ""
      operationId: "getJadepool"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "jadepool id"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
      security:
      - bearerAuth: []
    delete:
      tags:
      - "jadepool"
      summary: "delete a jadepool"
      description: ""
      operationId: "deleteJadepool"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "jadepool id"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
      security:
      - bearerAuth: []
  /blockchain:
    get:
      tags:
      - "blockchain"
      summary: "get blockchain list"
      description: ""
      operationId: "getBlockchainList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              status:
                type: "boolean"
              message:
                type: "string"
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Blockchain"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
      security:
      - bearerAuth: []
  /blockchain/new:
    post:
      tags:
      - "blockchain"
      summary: "create a blockchain"
      description: ""
      operationId: "newBlockchain"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "blockchain object"
        required: true
        schema:
          $ref: "#/definitions/Blockchain"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
      security:
      - bearerAuth: []
  /blockchain/{id}:
    put:
      tags:
      - "blockchain"
      summary: "update a blockchain"
      description: ""
      operationId: "updateBlockchain"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "blockchain id"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "blockchain object"
        required: true
        schema:
          $ref: "#/definitions/Blockchain"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
      security:
      - bearerAuth: []
    get:
      tags:
      - "jadepool"
      summary: "get a blockchain"
      description: ""
      operationId: "getBlockchain"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "blockchain id"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
      security:
      - bearerAuth: []
    delete:
      tags:
      - "blockchain"
      summary: "delete a blockchain"
      description: ""
      operationId: "deleteBlockchain"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "blockchain id"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
      security:
      - bearerAuth: []
  /asset:
    get:
      tags:
      - "asset"
      summary: "get asset list"
      description: ""
      operationId: "getAssetList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              status:
                type: "boolean"
              message:
                type: "string"
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Asset"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
      security:
      - bearerAuth: []
  /asset/new:
    post:
      tags:
      - "asset"
      summary: "create a asset"
      description: ""
      operationId: "newAsset"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "asset object"
        required: true
        schema:
          $ref: "#/definitions/Asset"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
      security:
      - bearerAuth: []
  /asset/{id}:
    put:
      tags:
      - "asset"
      summary: "update a asset"
      description: ""
      operationId: "updateAsset"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "asset id"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "asset object"
        required: true
        schema:
          $ref: "#/definitions/Asset"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
      security:
      - bearerAuth: []
    get:
      tags:
      - "asset"
      summary: "get a asset"
      description: ""
      operationId: "getAsset"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "asset id"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
      security:
      - bearerAuth: []
    delete:
      tags:
      - "asset"
      summary: "delete a asset"
      description: ""
      operationId: "deleteAsset"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "asset id"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Bad request"
        405:
          description: "Internal server error"
      security:
      - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT   
definitions:
  Account:
    type: "object"
    required:
    - "name"
    - "password"
    properties:
      name:
        type: "string"
      password:
        type: "string"
      companyID:
        type: "integer"
      lastName:
        type: "string"
      firstName:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
      type:
        type: "string"
        example: "SAAS_USER"
  Jadepool:
    type: "object"
    required:
    - "name"
    properties:
      id: 
        type: "integer"
      name:
        type: "string"
      description:
        type: "string"
      companyID:
        type: "integer"
      eccPubKey:
        type: "string"
      host:
        type: "string"
      port:
        type: "integer"
      version:
        type: "string"
  Blockchain:
    type: "object"
    required:
    - "name"
    properties:
      id: 
        type: "integer"
      name:
        type: "string"
      description:
        type: "string"
      confirmation:
        type: "integer"
  Asset:
    type: "object"
    required:
    - "name"
    properties:
      id: 
        type: "integer"
      name:
        type: "string"
      description:
        type: "string"
      decimal:
        type: "integer"
      cybname:
        type: "string"
      cybid:
        type: "string"
      withdrawFee:
        type: "string"
      depositFee:
        type: "string"
      lowWaterLevel:
        type: "string"
      highWaterLevel:
        type: "string"
      sweepTo:
        type: "string"
      smartContract:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      status:
        type: "boolean"
      message:
        type: "string"
      data:
        type: "object"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"